### ISSUE TITLE
Uncaught exceprion crashes node-red

### ISSUE THREAD

**Issue by juggledad** [webhookrelay/node-red-contrib-webhookrelay#2]
Node-RED version: v0.19.5
Node.js  version: v10.15.1
Darwin 17.7.0 x64 LE

Installed the node yeaterday and left NR running over night and today discovered NR had crashed. This is what is in the NR log. If there is anything else I can provide, Let me know.
```
subscribed to webhook stream successfully
15 Feb 02:30:33 - [info] [webhookrelay:a39408b7.282e58] webhook relay status event received: 'subscribed', message: 'subscribed to buckets: nodered'
15 Feb 02:30:42 - [info] [mqtt-broker:84f98d22.cf2c6] Disconnected from broker: mqtt://rosemarypi.local:1883
15 Feb 02:34:53 - [info] [mqtt-broker:84f98d22.cf2c6] Connected to broker: mqtt://rosemarypi.local:1883
pings are missing, reconnecting...
15 Feb 02:36:10 - [red] Uncaught Exception:
15 Feb 02:36:10 - Error: not opened
    at WebSocket.send (/Users/Paul/.node-red/node_modules/universal-websocket-client/node_modules/ws/lib/WebSocket.js:360:18)
    at WebhookRelayClient._sendMessage (/Users/Paul/.node-red/node_modules/webhookrelay-ws-client/lib/WebsocketClient.js:168:26)
    at WebhookRelayClient._receiveMessage (/Users/Paul/.node-red/node_modules/webhookrelay-ws-client/lib/WebsocketClient.js:187:26)
    at WebSocket._this._socket.onmessage (/Users/Paul/.node-red/node_modules/webhookrelay-ws-client/lib/WebsocketClient.js:75:35)
    at WebSocket.onMessage (/Users/Paul/.node-red/node_modules/universal-websocket-client/node_modules/ws/lib/EventTarget.js:99:16)
    at WebSocket.emit (events.js:189:13)
    at Receiver._receiver.onmessage (/Users/Paul/.node-red/node_modules/universal-websocket-client/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/Users/Paul/.node-red/node_modules/universal-websocket-client/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/Users/Paul/.node-red/node_modules/universal-websocket-client/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/Users/Paul/.node-red/node_modules/universal-websocket-client/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/Users/Paul/.node-red/node_modules/universal-websocket-client/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/Users/Paul/.node-red/node_modules/universal-websocket-client/node_modules/ws/lib/WebSocket.js:138:22)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Pauls-mini-3:.node-red Paul$ 

```

**Comment by rusenask** [comment]
Hi, seems like a race condition, I will fix this asap.

**Comment by rusenask** [comment]
hi @juggledad, should be fixed in 0.2.3. It took longer than expected but I have added some tests for the underlying websocket lib and also included it in my CI system.

**Comment by juggledad** [comment]
I'll reinstall it and let it sit awhile and see what comes up (hopefully nothing GRIN)

**Comment by rusenask** [comment]
thanks :)

**Comment by juggledad** [comment]
Well it has been running for more that 24 hours with out any issues

**Comment by rusenask** [comment]
great, reopen this if it happens again.
